//
//  PreListenHook.swift
//  My Dictionary
//
//  Created by Aleksandr Riakhin
//

import Foundation
import OpenAI

/// Pre-listen hook generated by AI to prepare user for the song
struct PreListenHook: Codable, JSONSchemaConvertible {
    let hook: String // Brief introduction (30-50 words)
    let targetPhrases: [TargetPhrase] // 3 key phrases to focus on
    let grammarHighlight: String? // Grammar point to watch for
    let culturalNote: String? // Brief cultural context
    
    struct TargetPhrase: Codable {
        let phrase: String
        let translation: String
        let cefr: String // CEFR level
        let context: String? // Where it appears in lyrics (optional)
    }
    
    static let example: Self = {
        .init(
            hook: "This vibrant Spanish song celebrates life and resilience. Pay attention to the use of present tense and expressions of joy.",
            targetPhrases: [
                TargetPhrase(
                    phrase: "La vida es un carnaval",
                    translation: "Life is a carnival",
                    cefr: "B1",
                    context: "Opening line of the chorus"
                ),
                TargetPhrase(
                    phrase: "todo tiene solución",
                    translation: "everything has a solution",
                    cefr: "B1",
                    context: "Main message of the song"
                ),
                TargetPhrase(
                    phrase: "no te rindas",
                    translation: "don't give up",
                    cefr: "B2",
                    context: "Encouragement line"
                )
            ],
            grammarHighlight: "Present tense (es, tiene) and imperative mood (no te rindas)",
            culturalNote: "This song is a celebration of resilience in Latin American culture, particularly in Cuba."
        )
    }()
}

