//
//  PreListenHook.swift
//  My Dictionary
//
//  Created by Aleksandr Riakhin
//

import Foundation
import OpenAI

/// Pre-listen hook generated by AI to prepare user for the song
struct PreListenHook: Codable, Hashable, JSONSchemaConvertible {
    let hook: String // Brief introduction (30-50 words)
    let targetPhrases: [TargetPhrase] // 3 key phrases to focus on
    let grammarHighlight: String? // Grammar point to watch for
    let culturalNote: String? // Brief cultural context
    let songCEFRLevel: CEFRLevel // CEFR level determined for the song (A1, A2, B1, etc.)

    struct TargetPhrase: Codable, Hashable {
        let phrase: String
        let cefr: CEFRLevel // CEFR level
        let meaning: String? // Where it appears in lyrics (optional)
    }
    
    static let example: Self = {
        .init(
            hook: "This vibrant Spanish song celebrates life and resilience. Pay attention to the use of present tense and expressions of joy.",
            targetPhrases: [
                TargetPhrase(
                    phrase: "La vida es un carnaval",
                    cefr: .b1,
                    meaning: "Life has its share of bad moments, but these will pass. You should choose to find joy and celebrate life, even amidst adversity."
                ),
                TargetPhrase(
                    phrase: "todo tiene solución",
                    cefr: .b1,
                    meaning: "It is used to give encouragement in times of difficulty or to emphasize the idea that things can be fixed."
                ),
                TargetPhrase(
                    phrase: "no te rindas",
                    cefr: .b2,
                    meaning: "You might say it to a friend who is struggling with a difficult task or to someone facing a hard time."
                )
            ],
            grammarHighlight: "Present tense (es, tiene) and imperative mood (no te rindas)",
            culturalNote: "This song is a celebration of resilience in Latin American culture, particularly in Cuba.",
            songCEFRLevel: .b1
        )
    }()
}

