import Foundation

enum Loc {
    // MARK: - Tab Bar
    enum TabBar {
        static let words = "tabbar.words"
        static let idioms = "tabbar.idioms"
        static let quizzes = "tabbar.quizzes"
        static let progress = "tabbar.progress"
        static let settings = "tabbar.settings"
    }

    // MARK: - Navigation Titles
    enum Navigation {
        static let wordDetails = "navigation.word_details"
        static let idiomDetails = "navigation.idiom_details"
        static let addTags = "navigation.add_tags"
        static let about = "navigation.about"
        static let quizResults = "navigation.quiz_results"
        static let spellingQuiz = "navigation.spelling_quiz"
        static let definitionQuiz = "navigation.definition_quiz"
    }

    // MARK: - Common Actions
    enum Actions {
        static let done = "actions.done"
        static let save = "actions.save"
        static let saveWord = "actions.save_word"
        static let cancel = "actions.cancel"
        static let delete = "actions.delete"
        static let edit = "actions.edit"
        static let add = "actions.add"
        static let next = "actions.next"
        static let back = "actions.back"
        static let exit = "actions.exit"
        static let ok = "actions.ok"
        static let yes = "actions.yes"
        static let no = "actions.no"
        static let tryAgain = "actions.try_again"
        static let viewAll = "actions.view_all"
        static let listen = "actions.listen"
        static let create = "actions.create"
        static let manage = "actions.manage"
        static let select = "actions.select"
        static let selectWord = "actions.select_word"
        static let selectIdiom = "actions.select_idiom"
        static let selectQuiz = "actions.select_quiz"
        static let signOut = "actions.sign_out"
        static let signIn = "actions.sign_in"
        static let upgrade = "actions.upgrade"
        static let learnMore = "actions.learn_more"
        static let copy = "actions.copy"
        static let refresh = "actions.refresh"
        static let clear = "actions.clear"
        static let reset = "actions.reset"
        static let test = "actions.test"
        static let check = "actions.check"
        static let verify = "actions.verify"
        static let show = "actions.show"
        static let send = "actions.send"
        static let request = "actions.request"
        static let sync = "actions.sync"
        static let upload = "actions.upload"
        static let download = "actions.download"
        static let importWords = "actions.import_words"
        static let exportWords = "actions.export_words"
        static let stopWatching = "actions.stop_watching"
        static let makeViewer = "actions.make_viewer"
        static let makeEditor = "actions.make_editor"
        static let remove = "actions.remove"
        static let skipForNow = "actions.skip_for_now"
        static let linkGoogle = "actions.link_google"
        static let linkApple = "actions.link_apple"
    }

    // MARK: - Onboarding
    enum Onboarding {
        static let welcomeTo = "onboarding.welcome_to"
        static let myDictionary = "onboarding.my_dictionary"
        static let personalVocabularyCompanion = "onboarding.personal_vocabulary_companion"
        static let buildYourVocabulary = "onboarding.build_your_vocabulary"
        static let personalizedLearning = "onboarding.personalized_learning"
        static let youreAllSet = "onboarding.youre_all_set"
        static let startBuildingVocabulary = "onboarding.start_building_vocabulary"
        static let getStarted = "onboarding.get_started"
        static let nextStep = "onboarding.next_step"
        static let personalWordList = "onboarding.personal_word_list"
        static let createOrganizeVocabulary = "onboarding.create_organize_vocabulary"
        static let findDefinitions = "onboarding.find_definitions"
        static let comprehensiveDefinitions = "onboarding.comprehensive_definitions"
        static let collectIdioms = "onboarding.collect_idioms"
        static let learnPracticeIdioms = "onboarding.learn_practice_idioms"
        static let smartQuizzes = "onboarding.smart_quizzes"
        static let adaptiveQuizzes = "onboarding.adaptive_quizzes"
        static let progressTracking = "onboarding.progress_tracking"
        static let visualInsights = "onboarding.visual_insights"
        static let collaborativeLearning = "onboarding.collaborative_learning"
        static let shareDictionaries = "onboarding.share_dictionaries"
    }

    // MARK: - Words
    enum Words {
        static let addWord = "words.add_word"
        static let addYourFirstWord = "words.add_your_first_word"
        static let addMoreWords = "words.add_more_words"
        static let addToSharedDictionary = "words.add_to_shared_dictionary"
        static let addNewWord = "words.add_new_word"
        static let deleteWord = "words.delete_word"
        static let deleteWordConfirmation = "words.delete_word_confirmation"
        static let transcription = "words.transcription"
        static let partOfSpeech = "words.part_of_speech"
        static let definition = "words.definition"
        static let difficulty = "words.difficulty"
        static let language = "words.language"
        static let inputLanguage = "words.input_language"
        static let tags = "words.tags"
        static let word = "words.word"
        static let words = "words.words"
        static let createTags = "words.create_tags"
        static let allWords = "words.all_words"
        static let favorite = "words.favorite"
        static let favoriteWords = "words.favorite_words"
        static let search = "words.search"
        static let searchWords = "words.search_words"
        static let searchResults = "words.search_results"
        static let tag = "words.tag"
        static let taggedWords = "words.tagged_words"
        static let new = "words.new"
        static let newWords = "words.new_words"
        static let inProgress = "words.in_progress"
        static let wordsInProgress = "words.words_in_progress"
        static let needsReview = "words.needs_review"
        static let wordsNeedingReview = "words.words_needing_review"
        static let mastered = "words.mastered"
        static let masteredWords = "words.mastered_words"
        static let wordsCount = "words.words_count"
        static let sort = "words.sort"
        static let filter = "words.filter"
        static let latestFirst = "words.latest_first"
        static let earliestFirst = "words.earliest_first"
        static let alphabetically = "words.alphabetically"
        static let byPartOfSpeech = "words.by_part_of_speech"
        static let typeWord = "words.type_word"
        static let sharedDictionary = "words.shared_dictionary"
        static let privateDictionary = "words.private_dictionary"
        static let impressiveVocabulary = "words.impressive_vocabulary"
        static let impressiveVocabularyMessage = "words.impressive_vocabulary_message"
        static let examples = "words.examples"
        static let noExamplesYet = "words.no_examples_yet"
        static let typeExampleHere = "words.type_example_here"
        static let addExample = "words.add_example"
        static let editExample = "words.edit_example"
    }

    // MARK: - Idioms
    enum Idioms {
        static let addIdiom = "idioms.add_idiom"
        static let addNewIdiom = "idioms.add_new_idiom"
        static let idiom = "idioms.idiom"
        static let idioms = "idioms.idioms"
        static let noIdiomsFound = "idioms.no_idioms_found"
        static let addThisIdiom = "idioms.add_this_idiom"
        static let beginAddIdioms = "idioms.begin_add_idioms"
        static let allIdioms = "idioms.all_idioms"
        static let favoriteIdioms = "idioms.favorite_idioms"
        static let foundIdioms = "idioms.found_idioms"
        static let examples = "idioms.examples"
        static let noExamplesYet = "idioms.no_examples_yet"
        static let typeExampleHere = "idioms.type_example_here"
        static let addExample = "idioms.add_example"
        static let editExample = "idioms.edit_example"
        static let deleteIdiom = "idioms.delete_idiom"
        static let deleteIdiomConfirmation = "idioms.delete_idiom_confirmation"
        static let searchIdioms = "idioms.search_idioms"
        static let favorites = "idioms.favorites"
        static let found = "idioms.found"
        static let idiomsCount = "idioms.idioms_count"
        static let sort = "idioms.sort"
        static let filter = "idioms.filter"
        static let latestFirst = "idioms.latest_first"
        static let earliestFirst = "idioms.earliest_first"
        static let alphabetically = "idioms.alphabetically"
    }

    // MARK: - Quizzes
    enum Quizzes {
        static let quizUnavailable = "quizzes.quiz_unavailable"
        static let backToQuizzes = "quizzes.back_to_quizzes"
        static let yourAnswer = "quizzes.your_answer"
        static let submitAnswer = "quizzes.submit_answer"
        static let nextWord = "quizzes.next_word"
        static let finish = "quizzes.finish"
        static let yourResults = "quizzes.your_results"
        static let finalScore = "quizzes.final_score"
        static let correctAnswers = "quizzes.correct_answers"
        static let bestStreak = "quizzes.best_streak"
        static let accuracy = "quizzes.accuracy"
        static let debug = "quizzes.debug"
        static let chooseCorrectDefinition = "quizzes.choose_correct_definition"
        static let word = "quizzes.word"
        static let quizTypes = "quizzes.quiz_types"
        static let practiceSettings = "quizzes.practice_settings"
        static let configureQuizExperience = "quizzes.configure_quiz_experience"
        static let practiceHardWordsOnly = "quizzes.practice_hard_words_only"
        static let focusWordsNeedReview = "quizzes.focus_words_need_review"
        static let notEnoughWordsReview = "quizzes.not_enough_words_review"
        static let wordsPerSession = "quizzes.words_per_session"
        static let numberWords = "quizzes.number_words"
        static let selectDictionary = "quizzes.select_dictionary"
        static let noDifficultWordsAvailable = "quizzes.no_difficult_words_available"
        static let spellingQuizDescription = "quizzes.spelling_quiz_description"
        static let definitionQuizDescription = "quizzes.definition_quiz_description"
        static let progress = "quizzes.progress"
        static let streak = "quizzes.streak"
        static let score = "quizzes.score"
        static let best = "quizzes.best"
        static let hint = "quizzes.hint"
        static let attempt = "quizzes.attempt"
        static let correct = "quizzes.correct"
        static let wellDone = "quizzes.well_done"
        static let keepUpGoodWork = "quizzes.keep_up_good_work"
        static let correctWordIs = "quizzes.correct_word_is"
        static let movingToNextWord = "quizzes.moving_to_next_word"
        static let incorrect = "quizzes.incorrect"
        static let movingToNextQuestion = "quizzes.moving_to_next_question"
        static let quizComplete = "quizzes.quiz_complete"
        static let greatJobCompletedSpellingQuiz = "quizzes.great_job_completed_spelling_quiz"
        static let greatJobCompletedDefinitionQuiz = "quizzes.great_job_completed_definition_quiz"
        static let skipWord = "quizzes.skip_word"
        static let incorrectMovingToNextQuestion = "quizzes.incorrect_moving_to_next_question"
        static let contributions = "quizzes.contributions"
        static let notEnoughWordsAvailable = "quizzes.not_enough_words_available"
        static let needAtLeastWords = "quizzes.need_at_least_words"
        static let sharedDictionaryNeedsMoreWords = "quizzes.shared_dictionary_needs_more_words"
        static let startBuildingVocabulary = "quizzes.start_building_vocabulary"
        static let keepAddingWords = "quizzes.keep_adding_words"
        static let askDictionaryOwnerAddWords = "quizzes.ask_dictionary_owner_add_words"
        static let switchDifferentDictionary = "quizzes.switch_different_dictionary"
        static let addWordsToSharedDictionary = "quizzes.add_words_to_shared_dictionary"
        static let addYourFirstWord = "quizzes.add_your_first_word"
        static let addMoreWords = "quizzes.add_more_words"
        static let youCanPracticeVocabulary = "quizzes.you_can_practice_vocabulary"
        static let selectSharedDictionaryPopulated = "quizzes.select_shared_dictionary_populated"
        static let numberWordsPracticeSession = "quizzes.number_words_practice_session"
        static let minWords = "quizzes.min_words"
        static let maxWords = "quizzes.max_words"
        static let sharedDictionaryNeedsHardWords = "quizzes.shared_dictionary_needs_hard_words"
        static let needsAtLeastHardWord = "quizzes.needs_at_least_hard_word"
        static let currentlyHasHardWords = "quizzes.currently_has_hard_words"
        static let needsAtLeastWordsStartQuizzes = "quizzes.needs_at_least_words_start_quizzes"
        static let currentlyHasWords = "quizzes.currently_has_words"
        static let needAtLeastHardWordPractice = "quizzes.need_at_least_hard_word_practice"
        static let currentlyHaveHardWords = "quizzes.currently_have_hard_words"
        static let needAtLeastWordsStartQuizzes = "quizzes.need_at_least_words_start_quizzes"
        static let currentlyHaveWords = "quizzes.currently_have_words"
    }

    // MARK: - Analytics
    enum Analytics {
        static let overview = "analytics.overview"
        static let recentQuizResults = "analytics.recent_quiz_results"
        static let noQuizResultsYet = "analytics.no_quiz_results_yet"
        static let completeFirstQuiz = "analytics.complete_first_quiz"
        static let vocabularyGrowth = "analytics.vocabulary_growth"
        static let noGrowthDataYet = "analytics.no_growth_data_yet"
        static let completeQuizzesGrowth = "analytics.complete_quizzes_growth"
        static let timePeriod = "analytics.time_period"
        static let week = "analytics.week"
        static let month = "analytics.month"
        static let year = "analytics.year"
        static let practiceTime = "analytics.practice_time"
        static let sessions = "analytics.sessions"
        static let allResults = "analytics.all_results"
        static let duration = "analytics.duration"
    }

    // MARK: - Settings
    enum Settings {
        static let translateDefinitions = "settings.translate_definitions"
        static let showDefinitionsNativeLanguage = "settings.show_definitions_native_language"
        static let accent = "settings.accent"
        static let selectAccent = "settings.select_accent"
        static let notifications = "settings.notifications"
        static let dailyReminders = "settings.daily_reminders"
        static let difficultWords = "settings.difficult_words"
        static let subscription = "settings.subscription"
        static let proUser = "settings.pro_user"
        static let freePlan = "settings.free_plan"
        static let limitedFeaturesAvailable = "settings.limited_features_available"
        static let signedInAs = "settings.signed_in_as"
        static let anonymous = "settings.anonymous"
        static let uploadBackupGoogle = "settings.upload_backup_google"
        static let downloadBackupGoogle = "settings.download_backup_google"
        static let signInSyncWordLists = "settings.sign_in_sync_word_lists"
        static let organization = "settings.organization"
        static let showIdiomsTab = "settings.show_idioms_tab"
        static let sharedDictionaries = "settings.shared_dictionaries"
        static let aboutApp = "settings.about_app"
        static let features = "settings.features"
        static let addOrganizeWords = "settings.add_organize_words"
        static let practiceQuizzesSpelling = "settings.practice_quizzes_spelling"
        static let trackLearningProgress = "settings.track_learning_progress"
        static let importExportWordCollection = "settings.import_export_word_collection"
        static let customizeLearningExperience = "settings.customize_learning_experience"
        static let voicePronunciationSupport = "settings.voice_pronunciation_support"
        static let contactMe = "settings.contact_me"
        static let xTwitter = "settings.x_twitter"
        static let instagram = "settings.instagram"
        static let support = "settings.support"
        static let rateApp = "settings.rate_app"
        static let exportSuccessful = "settings.export_successful"
        static let uploadSuccessful = "settings.upload_successful"
        static let downloadSuccessful = "settings.download_successful"
    }

    // MARK: - Authentication
    enum Auth {
        static let signInBeforeSubscribing = "auth.sign_in_before_subscribing"
        static let signInWithGoogle = "auth.sign_in_with_google"
        static let canAlwaysSignInLater = "auth.can_always_sign_in_later"
        static let linkAdditionalAccounts = "auth.link_additional_accounts"
        static let accountsLinkedSuccessfully = "auth.accounts_linked_successfully"
        static let signOutConfirmation = "auth.sign_out_confirmation"
        static let yourWordsAreSafe = "auth.your_words_are_safe"
        static let cloudSyncDisabled = "auth.cloud_sync_disabled"
    }

    // MARK: - Shared Dictionaries
    enum SharedDictionaries {
        static let dictionarySelected = "shared_dictionaries.dictionary_selected"
        static let name = "shared_dictionaries.name"
        static let created = "shared_dictionaries.created"
        static let yourRole = "shared_dictionaries.your_role"
        static let owner = "shared_dictionaries.owner"
        static let editor = "shared_dictionaries.editor"
        static let viewer = "shared_dictionaries.viewer"
        static let editorDescription = "shared_dictionaries.editor_description"
        static let canAddEditDeleteWords = "shared_dictionaries.can_add_edit_delete_words"
        static let canInviteCollaborators = "shared_dictionaries.can_invite_collaborators"
        static let canManageDictionarySettings = "shared_dictionaries.can_manage_dictionary_settings"
        static let viewerDescription = "shared_dictionaries.viewer_description"
        static let canViewAllWords = "shared_dictionaries.can_view_all_words"
        static let cannotMakeChanges = "shared_dictionaries.cannot_make_changes"
        static let cannotInviteOthers = "shared_dictionaries.cannot_invite_others"
        static let collaboratorAddedEmailName = "shared_dictionaries.collaborator_added_email_name"
        static let ofDictionaryCreated = "shared_dictionaries.of_dictionary_created"
        static let freeUsersOneDictionary = "shared_dictionaries.free_users_one_dictionary"
        static let createSharedDictionary = "shared_dictionaries.create_shared_dictionary"
        static let collaborateOthers = "shared_dictionaries.collaborate_others"
        static let deleteDictionary = "shared_dictionaries.delete_dictionary"
        static let yourDictionaries = "shared_dictionaries.your_dictionaries"
        static let dictionaryCountCreated = "shared_dictionaries.dictionary_count_created"
        static let noSharedDictionaries = "shared_dictionaries.no_shared_dictionaries"
        static let createSharedDictionaryCollaborate = "shared_dictionaries.create_shared_dictionary_collaborate"
        static let dictionaries = "shared_dictionaries.dictionaries"
        static let enterDictionaryName = "shared_dictionaries.enter_dictionary_name"
        static let newSharedDictionary = "shared_dictionaries.new_shared_dictionary"
        static let dictionaryNameRequired = "shared_dictionaries.dictionary_name_required"
        static let signInToCreateSharedDictionary = "shared_dictionaries.sign_in_to_create_shared_dictionary"
        static let collaborators = "shared_dictionaries.collaborators"
        static let createdBy = "shared_dictionaries.created_by"
        static let noWordsYet = "shared_dictionaries.no_words_yet"
        static let addWordsToSharedDictionary = "shared_dictionaries.add_words_to_shared_dictionary"
        static let noResults = "shared_dictionaries.no_results"
        static let noWordsMatchFilter = "shared_dictionaries.no_words_match_filter"
        static let dictionaryDetails = "shared_dictionaries.dictionary_details"
    }

    // MARK: - Tags
    enum Tags {
        static let manageTags = "tags.manage_tags"
        static let tagsHelpText = "tags.tags_help_text"
        static let noTagsYet = "tags.no_tags_yet"
        static let addFirstTag = "tags.add_first_tag"
        static let addTag = "tags.add_tag"
        static let deleteTag = "tags.delete_tag"
        static let deleteTagConfirmation = "tags.delete_tag_confirmation"
        static let deleteTagCannotUndo = "tags.delete_tag_cannot_undo"
        static let tagName = "tags.tag_name"
        static let tagNameHelp = "tags.tag_name_help"
        static let typeTagName = "tags.type_tag_name"
        static let tagColor = "tags.tag_color"
        static let tagColorHelp = "tags.tag_color_help"
        static let editTag = "tags.edit_tag"
        static let newTag = "tags.new_tag"
        static let tagManagementError = "tags.tag_management_error"
    }

    // MARK: - Coffee Banner
    enum Coffee {
        static let buyMeACoffee = "coffee.buy_me_a_coffee"
        static let maybeLater = "coffee.maybe_later"
    }

    // MARK: - Paywall
    enum Paywall {
        static let termsOfService = "paywall.terms_of_service"
        static let privacyPolicy = "paywall.privacy_policy"
        static let upgradeToPro = "paywall.upgrade_to_pro"
        static let restorePurchases = "paywall.restore_purchases"
        static let trackProgress = "paywall.track_progress"
        static let seeYourImprovement = "paywall.see_your_improvement"
        static let collaborate = "paywall.collaborate"
        static let learnWithOthers = "paywall.learn_with_others"
        static let everythingYouNeedToMasterVocabulary = "paywall.everything_you_need_to_master_vocabulary"
        static let chooseYourPlan = "paywall.choose_your_plan"
        static let startPro = "paywall.start_pro"
        static let trustedByLearnersWorldwide = "paywall.trusted_by_learners_worldwide"
        static let appStoreRating = "paywall.app_store_rating"
        static let activeUsers = "paywall.active_users"
        static let wordsAdded = "paywall.words_added"
        static let signInRequired = "paywall.sign_in_required"
    }

    // MARK: - Pro Features
    enum ProFeatures {
        static let googleSync = "pro_features.google_sync"
        static let unlimitedExport = "pro_features.unlimited_export"
        static let createSharedDictionaries = "pro_features.create_shared_dictionaries"
        static let advancedAnalytics = "pro_features.advanced_analytics"
        static let prioritySupport = "pro_features.priority_support"
        static let proFeatures = "pro_features.pro_features"
        static let tagManagement = "pro_features.tag_management"
        static let syncWordsAcrossDevices = "pro_features.sync_words_across_devices"
        static let exportUnlimitedWords = "pro_features.export_unlimited_words"
        static let createManageSharedDictionaries = "pro_features.create_manage_shared_dictionaries"
        static let detailedInsights = "pro_features.detailed_insights"
        static let prioritySupportTeam = "pro_features.priority_support_team"
        static let unlockAllProFeatures = "pro_features.unlock_all_pro_features"
        static let organizeWordsWithTags = "pro_features.organize_words_with_tags"
        static let detailedProgressTracking = "pro_features.detailed_progress_tracking"
        static let getPrioritySupport = "pro_features.get_priority_support"
    }

    // MARK: - Error Messages
    enum Errors {
        static let errorUpdatingWordExamples = "errors.error_updating_word_examples"
        static let errorRemovingWord = "errors.error_removing_word"
        static let errorSavingWord = "errors.error_saving_word"
        static let errorUpdatingIdiomExamples = "errors.error_updating_idiom_examples"
        static let errorRemovingIdiom = "errors.error_removing_idiom"
        static let errorSavingIdiom = "errors.error_saving_idiom"
        static let inputNotWord = "errors.input_not_word"
        static let inputCannotBeEmpty = "errors.input_cannot_be_empty"
        static let deviceMutedOrVolumeLow = "errors.device_muted_or_volume_low"
        static let cannotPlayAudio = "errors.cannot_play_audio"
        static let cannotSetupAudioSession = "errors.cannot_setup_audio_session"
        static let exportFailed = "errors.export_failed"
        static let importFailed = "errors.import_failed"
        static let cannotAccessSecurityScopedResource = "errors.cannot_access_security_scoped_resource"
        static let tagAlreadyExists = "errors.tag_already_exists"
        static let tagAlreadyAssignedToWord = "errors.tag_already_assigned_to_word"
        static let tagNotAssignedToWord = "errors.tag_not_assigned_to_word"
        static let authenticationRequired = "errors.authentication_required"
        static let noActiveSubscriptionsFound = "errors.no_active_subscriptions_found"
        static let failedToUpdateWordProgress = "errors.failed_to_update_word_progress"
        static let failedToUpdateWordDifficultyLevel = "errors.failed_to_update_word_difficulty_level"
        static let failedToSaveQuizSession = "errors.failed_to_save_quiz_session"
        static let failedToUpdateUserStatistics = "errors.failed_to_update_user_statistics"
        static let invalidWordId = "errors.invalid_word_id"
        static let wordNotFound = "errors.word_not_found"
        static let failedToCalculateProgress = "errors.failed_to_calculate_progress"
        static let invalidTranslationUrl = "errors.invalid_translation_url"
        static let networkErrorDuringTranslation = "errors.network_error_during_translation"
        static let invalidResponseFromTranslationService = "errors.invalid_response_from_translation_service"
        static let translationFailed = "errors.translation_failed"
        static let invalidUserEmail = "errors.invalid_user_email"
        static let networkErrorOccurred = "errors.network_error_occurred"
        static let syncFailed = "errors.sync_failed"
        static let invalidInputProvided = "errors.invalid_input_provided"
        static let dictionaryNotFound = "errors.dictionary_not_found"
        static let noSubscriptionOfferingsAvailable = "errors.no_subscription_offerings_available"
        static let requestedSubscriptionPackageNotFound = "errors.requested_subscription_package_not_found"
        static let purchaseCouldNotBeCompleted = "errors.purchase_could_not_be_completed"
        static let failedToRestorePreviousPurchases = "errors.failed_to_restore_previous_purchases"
        static let exportLimitExceeded = "errors.export_limit_exceeded"
        static let maxTagsReached = "errors.max_tags_reached"
        static let tagAlreadyAssigned = "errors.tag_already_assigned"
        static let tagNotAssigned = "errors.tag_not_assigned"
        static let networkTimeout = "errors.network_timeout"
        static let serverUnreachable = "errors.server_unreachable"
        static let invalidResponse = "errors.invalid_response"
        static let noInternetConnection = "errors.no_internet_connection"
        static let missingAPIKey = "errors.missing_api_key"
        static let decodingError = "errors.decoding_error"
        static let invalidURL = "errors.invalid_url"
        static let noData = "errors.no_data"
        static let saveFailed = "errors.save_failed"
        static let readFailed = "errors.read_failed"
        static let dataCorrupted = "errors.data_corrupted"
        static let invalidInput = "errors.invalid_input"
        static let missingField = "errors.missing_field"
        static let unknownError = "errors.unknown_error"
    }

    // MARK: - Empty States
    enum EmptyStates {
        static let noIdiomsYet = "empty_states.no_idioms_yet"
        static let noFavoriteWords = "empty_states.no_favorite_words"
        static let noSearchResults = "empty_states.no_search_results"
        static let startImprovingVocabulary = "empty_states.start_improving_vocabulary"
        static let tapHeartIconToAddFavorites = "empty_states.tap_heart_icon_to_add_favorites"
        static let tryDifferentSearchTerm = "empty_states.try_different_search_term"
    }

    // MARK: - Auto Detect
    enum AutoDetect {
        static let autoDetect = "auto_detect.auto_detect"
    }
}
