//
//  IdiomProgress+CoreDataClass.swift
//  My Dictionary
//
//  Created by Aleksandr Riakhin on 3/8/25.
//

import Foundation
import CoreData

@objc(CDIdiomProgress)
final class CDIdiomProgress: NSManagedObject, Identifiable {
    // This class will be automatically generated by Core Data
}
