//
//  MusicRecommendationService.swift
//  My Dictionary
//
//  Created by Aleksandr Riakhin
//

import Foundation
import FirebaseFirestore

/// Service for managing music recommendations with Firestore caching
/// Path: recommendationItems/{language.rawValue}/{cefrLevel}
final class MusicRecommendationService {
    
    static let shared = MusicRecommendationService()
    
    private let db = Firestore.firestore()
    private let aiService = AIService.shared
    private let appleMusicService = AppleMusicService.shared
    
    private init() {}
    
    // MARK: - Public Methods
    
    /// Get recommendations from Firestore cache
    /// Path: recommendationItems/{languageCode}/{cefrLevel}
    /// - Parameters:
    ///   - language: InputLanguage (e.g., ".english", ".spanish")
    ///   - cefrLevel: CEFR level (e.g., "B1", "A2")
    /// - Returns: FirestoreRecommendation if found, nil otherwise
    func getRecommendations(language: InputLanguage, cefrLevel: String) async throws -> FirestoreRecommendation? {
        let docRef = db.collection("recommendationItems")
            .document(language.rawValue)
            .collection(cefrLevel)
            .document("recommendations")
        
        print("📥 [MusicRecommendationService] Fetching from Firestore: recommendationItems/\(language.englishName)/\(cefrLevel)/recommendations")

        let document = try await docRef.getDocument()
        
        guard document.exists else {
            print("ℹ️ [MusicRecommendationService] Document does not exist in Firestore")
            return nil
        }
        
        guard let data = document.data() else {
            print("⚠️ [MusicRecommendationService] Document exists but has no data")
            return nil
        }
        
        print("✅ [MusicRecommendationService] Found document in Firestore")
        
        // Convert Firestore Timestamp to ISO8601 string before serialization
        var convertedData = data
        if let timestamp = data["generated_at"] as? Timestamp {
            let date = timestamp.dateValue()
            let formatter = ISO8601DateFormatter()
            convertedData["generated_at"] = formatter.string(from: date)
        }
        
        // Convert Firestore data to FirestoreRecommendation
        let jsonData = try JSONSerialization.data(withJSONObject: convertedData)
        let decoder = JSONDecoder()
        
        // Handle Date decoding from ISO8601 string
        decoder.dateDecodingStrategy = .iso8601
        
        let recommendation = try decoder.decode(FirestoreRecommendation.self, from: jsonData)
        return recommendation
    }
    
    /// Save recommendations to Firestore
    /// - Parameters:
    ///   - recommendation: The recommendation to save
    ///   - language: InputLanguage
    ///   - cefrLevel: CEFR level
    func saveRecommendations(_ recommendation: FirestoreRecommendation, language: InputLanguage, cefrLevel: String) async throws {
        print("💾 [MusicRecommendationService] saveRecommendations() called - Source: \(recommendation.artists.isEmpty && recommendation.albums.isEmpty ? "Search" : "AI")")
        let docRef = db.collection("recommendationItems")
            .document(language.rawValue)
            .collection(cefrLevel)
            .document("recommendations")
        
        // Convert to dictionary for Firestore
        let encoder = JSONEncoder()
        let jsonData = try encoder.encode(recommendation)
        var dictionary = try JSONSerialization.jsonObject(with: jsonData) as? [String: Any] ?? [:]
        
        // Convert Date to Timestamp
        dictionary["generated_at"] = Timestamp(date: recommendation.generatedAt)
        
        print("💾 [MusicRecommendationService] Writing to Firestore document...")
        try await docRef.setData(dictionary, merge: false)
        print("✅ [MusicRecommendationService] Successfully wrote to Firestore: recommendationItems/\(language.englishName)/\(cefrLevel)/recommendations")
    }
    
    /// Generate recommendations using OpenAI
    /// - Parameters:
    ///   - language: InputLanguage
    ///   - cefrLevel: CEFR level
    ///   - userProfile: User profile for personalization
    /// - Returns: FirestoreRecommendation generated by AI
    func generateRecommendationsWithAI(language: InputLanguage, cefrLevel: String, userProfile: UserOnboardingProfile) async throws -> FirestoreRecommendation {
        print("🤖 [MusicRecommendationService] Starting OpenAI recommendation generation...")
        
        guard aiService.canMakeAIRequest() else {
            print("❌ [MusicRecommendationService] AI request not allowed (Pro required)")
            throw AIError.proRequired
        }
        
        guard let cefrLevelEnum = CEFRLevel(rawValue: cefrLevel) else {
            print("❌ [MusicRecommendationService] Invalid CEFR level: \(cefrLevel)")
            throw MusicError.invalidCEFRLevel
        }
        
        print("🤖 [MusicRecommendationService] Making OpenAI request for \(language.englishName)/\(cefrLevel)...")
        print("🤖 [MusicRecommendationService] Request details - User: \(userProfile.userName), Languages: \(userProfile.studyLanguages.map { $0.language.rawValue }.joined(separator: ", "))")
        
        // Request AI recommendations
        let aiResponse: AIMusicRecommendationsResponse
        do {
            aiResponse = try await aiService.request(
                .musicRecommendations(
                    language: language,
                    cefrLevel: cefrLevelEnum,
                    userProfile: userProfile
                )
            )
            print("✅ [MusicRecommendationService] Received response from OpenAI: \(aiResponse.artists.count) artists, \(aiResponse.albums.count) albums, \(aiResponse.songs.count) songs")
        } catch {
            print("❌ [MusicRecommendationService] OpenAI request failed with error: \(error)")
            print("❌ [MusicRecommendationService] Error type: \(type(of: error))")
            print("❌ [MusicRecommendationService] Error description: \(error.localizedDescription)")
            throw error // Re-throw to let caller handle
        }
        
        // Convert AI response to FirestoreRecommendation
        print("🔄 [MusicRecommendationService] Converting AI response to FirestoreRecommendation...")
        let recommendation = convertAIResponseToFirestoreRecommendation(
            aiResponse,
            language: language,
            cefrLevel: cefrLevel
        )
        print("✅ [MusicRecommendationService] Converted to FirestoreRecommendation: \(recommendation.artists.count) artists, \(recommendation.albums.count) albums, \(recommendation.songs.count) songs")
        
        // Save to Firestore immediately so next user gets it from cache
        print("💾 [MusicRecommendationService] Saving recommendations to Firestore...")
        try await saveRecommendations(recommendation, language: language, cefrLevel: cefrLevel)
        print("✅ [MusicRecommendationService] Saved recommendations for \(language.englishName)/\(cefrLevel)")

        // After saving, search Apple Music to get actual songs with artwork
        // Convert artists/albums to songs, then search for all songs
        print("🔍 [MusicRecommendationService] Searching Apple Music for actual songs...")
        let songsWithArtwork = try await convertRecommendationsToSongs(recommendation)
        
        // Create a new recommendation with only songs (for "Your Daily 5")
        let songsOnlyRecommendation = FirestoreRecommendation(
            languageCode: language.rawValue,
            cefrLevel: cefrLevel,
            artists: [], // Don't include artists/albums in final recommendation
            albums: [],
            songs: songsWithArtwork,
            generatedAt: Date(),
            version: 1
        )
        
        // Save the songs-only version to Firestore
        print("💾 [MusicRecommendationService] Saving songs-only recommendations to Firestore...")
        try await saveRecommendations(songsOnlyRecommendation, language: language, cefrLevel: cefrLevel)
        print("✅ [MusicRecommendationService] Saved \(songsWithArtwork.count) songs to Firestore")
        
        return songsOnlyRecommendation
    }
    
    /// Generate recommendations using Apple Music search (fallback)
    /// - Parameters:
    ///   - language: InputLanguage
    ///   - cefrLevel: CEFR level
    /// - Returns: FirestoreRecommendation generated from search
    func generateRecommendationsWithSearch(language: InputLanguage, cefrLevel: String) async throws -> FirestoreRecommendation {
        guard appleMusicService.isAuthorized else {
            throw MusicError.authenticationRequired
        }
        
        // Search for popular songs in the language
        let songs = try await appleMusicService.searchSongs(query: language.englishName, language: language.englishName)

        // Convert to FirestoreRecommendation format
        // For search fallback, we still only store names (not IDs) since IDs vary by region
        let recommendationSongs = Array(songs.prefix(20)).map { song in
            RecommendationSong(
                title: song.title,
                artist: song.artist,
                reason: "Popular song in \(language.englishName)"
            )
        }
        
        let recommendation = FirestoreRecommendation(
            languageCode: language.rawValue,
            cefrLevel: cefrLevel,
            artists: [],
            albums: [],
            songs: recommendationSongs,
            generatedAt: Date(),
            version: 1
        )
        
        print("💾 [MusicRecommendationService] Saving search-based recommendations to Firestore...")
        // Save to Firestore for future cache hits
        try? await saveRecommendations(recommendation, language: language, cefrLevel: cefrLevel)
        print("✅ [MusicRecommendationService] Saved search-based recommendations for \(language.englishName)/\(cefrLevel)")
        
        return recommendation
    }
    
    // MARK: - Private Methods
    
    /// Convert recommendations to actual songs by searching Apple Music
    /// For artists/albums, gets random songs. For songs, searches by name.
    private func convertRecommendationsToSongs(_ recommendation: FirestoreRecommendation) async throws -> [RecommendationSong] {
        guard appleMusicService.isAuthorized else {
            throw MusicError.authenticationRequired
        }
        
        var allSongs: [RecommendationSong] = []
        
        // 1. Convert artist recommendations to songs
        for artist in recommendation.artists {
            do {
                // Search for songs by artist name directly
                let songs = try await appleMusicService.getArtistSongs(artistName: artist.name, limit: 20)
                if let randomSong = songs.randomElement() {
                    allSongs.append(RecommendationSong(
                        title: randomSong.title,
                        artist: randomSong.artist,
                        reason: artist.reason ?? "Recommended artist"
                    ))
                    print("✅ [MusicRecommendationService] Found random song for artist \(artist.name): \(randomSong.title)")
                } else {
                    print("⚠️ [MusicRecommendationService] No songs found for artist \(artist.name)")
                }
            } catch {
                print("⚠️ [MusicRecommendationService] Failed to get songs for artist \(artist.name): \(error.localizedDescription)")
                continue
            }
        }
        
        // 2. Convert album recommendations to songs
        for album in recommendation.albums {
            do {
                // Search for songs from album by name and artist
                let songs = try await appleMusicService.getAlbumSongs(albumName: album.name, artistName: album.artist)
                if let randomSong = songs.randomElement() {
                    allSongs.append(RecommendationSong(
                        title: randomSong.title,
                        artist: randomSong.artist,
                        reason: album.reason ?? "Recommended album"
                    ))
                    print("✅ [MusicRecommendationService] Found random song for album \(album.name): \(randomSong.title)")
                } else {
                    print("⚠️ [MusicRecommendationService] No songs found for album \(album.name)")
                }
            } catch {
                print("⚠️ [MusicRecommendationService] Failed to get songs for album \(album.name): \(error.localizedDescription)")
                continue
            }
        }
        
        // 3. Search for song recommendations
        for song in recommendation.songs {
            do {
                let query = "\(song.title) \(song.artist)"
                let songs = try await appleMusicService.searchSongs(query: query, language: nil)
                if let foundSong = songs.first(where: {
                    $0.title.lowercased().contains(song.title.lowercased()) &&
                    $0.artist.lowercased().contains(song.artist.lowercased())
                }) ?? songs.first {
                    // Song found - keep the recommendation with reason
                    allSongs.append(RecommendationSong(
                        title: foundSong.title,
                        artist: foundSong.artist,
                        reason: song.reason
                    ))
                }
            } catch {
                print("⚠️ [MusicRecommendationService] Failed to find song \(song.title): \(error)")
                // Keep the original recommendation even if search fails
                allSongs.append(song)
            }
        }
        
        // Remove duplicates
        var uniqueSongs: [RecommendationSong] = []
        var seen = Set<String>()
        for song in allSongs {
            let key = "\(song.title.lowercased())-\(song.artist.lowercased())"
            if !seen.contains(key) {
                uniqueSongs.append(song)
                seen.insert(key)
            }
        }
        
        print("✅ [MusicRecommendationService] Converted to \(uniqueSongs.count) unique songs")
        return uniqueSongs
    }
    
    /// Convert AI response to FirestoreRecommendation
    /// OpenAI only provides names and reasons - no IDs or URLs
    private func convertAIResponseToFirestoreRecommendation(
        _ aiResponse: AIMusicRecommendationsResponse,
        language: InputLanguage,
        cefrLevel: String
    ) -> FirestoreRecommendation {
        let artists = aiResponse.artists.map { item in
            RecommendationArtist(
                name: item.title, // OpenAI provides artist name as title
                reason: item.reason
            )
        }
        
        let albums = aiResponse.albums.map { item in
            RecommendationAlbum(
                name: item.title, // OpenAI provides album name as title
                artist: item.artist,
                reason: item.reason
            )
        }
        
        let songs = aiResponse.songs.map { item in
            RecommendationSong(
                title: item.title, // OpenAI provides song title
                artist: item.artist,
                reason: item.reason
            )
        }
        
        return FirestoreRecommendation(
            languageCode: language.rawValue,
            cefrLevel: cefrLevel,
            artists: artists,
            albums: albums,
            songs: songs,
            generatedAt: Date(),
            version: 1
        )
    }
}

